name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "/" # App source code path
          api_location: "" # Api source code path - set to empty if no API
          output_location: "build" # Built app content directory - e.g. build
          app_build_command: "npm run build"
        env:
          REACT_APP_AZURE_CLIENT_ID: ${{ secrets.REACT_APP_AZURE_CLIENT_ID }}
          REACT_APP_AZURE_TENANT_ID: ${{ secrets.REACT_APP_AZURE_TENANT_ID }}
          REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}
          REACT_APP_SHAREPOINT_SITE_ID: ${{ secrets.REACT_APP_SHAREPOINT_SITE_ID }}
          REACT_APP_SHAREPOINT_DRIVE_ID: ${{ secrets.REACT_APP_SHAREPOINT_DRIVE_ID }}
          REACT_APP_SHAREPOINT_FOLDER_ID: ${{ secrets.REACT_APP_SHAREPOINT_FOLDER_ID }}
          REACT_APP_SQL_SERVER: ${{ secrets.REACT_APP_SQL_SERVER }}
          REACT_APP_SQL_DATABASE: ${{ secrets.REACT_APP_SQL_DATABASE }}
          REACT_APP_SQL_USER: ${{ secrets.REACT_APP_SQL_USER }}
          REACT_APP_SQL_PASSWORD: ${{ secrets.REACT_APP_SQL_PASSWORD }}
          REACT_APP_SQL_PORT: ${{ secrets.REACT_APP_SQL_PORT }}
          REACT_APP_SQL_ENCRYPT: ${{ secrets.REACT_APP_SQL_ENCRYPT }}
          REACT_APP_SQL_TRUST_SERVER_CERTIFICATE: ${{ secrets.REACT_APP_SQL_TRUST_SERVER_CERTIFICATE }}
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          REACT_APP_USE_SHAREPOINT_SYNC: ${{ secrets.REACT_APP_USE_SHAREPOINT_SYNC }}
          REACT_APP_USE_SQL_DATABASE: ${{ secrets.REACT_APP_USE_SQL_DATABASE }}
          REACT_APP_USE_LOCAL_STORAGE: ${{ secrets.REACT_APP_USE_LOCAL_STORAGE }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close" 